import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'


const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Shop Customer Data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen bg-[#023047] justify-center items-center'>
        <h1 className='text-[#ffb703] text-4xl animate-bounce font-bold tracking-widest'>Hello World</h1>
      </main>
    </>
  )
}
